export const TOP_SKILLS = [
    "Data Entry Specialist",
    "Vide Editors",
    "Data Analyst",
    "Shopify Developer",
    "Ruby on Rails Developer",
    "Andriod Developer",
    "Bookkeeper"
];

export const ALL_SKILLLS = [
    "Data Entry Specialist",
    "Vide Editors",
    "Data Analyst",
    "Shopify Developer",
    "Ruby on Rails Developer",
    "Mobile App Developer",
    "PHP developer",
    "Python Developer",
    "Resume Writer",
    "SEO Expert",
    "Social Media Manager",
    "Software Developer",
    "Software Engineer",
    "Technical Wroter",
    "UI Designer",
    "UX Designer",
    "Virtual Assistant",
    "Graphic Designer",
    "Javascript Developer",
    "Logo Designer",
    "Mobile App Developer",
    "PHP developer",
    "Python Developer",
]
export const TRENDING_SKILLS = [
    "Data Entry Specialist",
    "Vide Editors",
    "Data Analyst",
    "Shopify Developer",
    "Ruby on Rails Developer",
    "Mobile App Developer",
    "PHP developer",
    "Python Developer",
    "Resume Writer",
    "SEO Expert",
    "Social Media Manager",
    "Software Developer",
    "Software Engineer",
    "Technical Wroter",
    "UI Designer",
    "UX Designer",
    "Virtual Assistant",
];
export const US_SKILLS = [
    "Graphic Designer",
    "Javascript Developer",
    "Logo Designer",
    "Mobile App Developer",
    "PHP developer",
    "Python Developer",
    "Resume Writer",
    "SEO Expert",
    "Social Media Manager",
    "Software Developer",
    "Software Engineer",
    "Technical Wroter",
    "UI Designer",
    "UX Designer",
    "Virtual Assistant",
];
export const CATALOG = [
    "Data Entry Specialist",
    "Resume Writer",
    "SEO Expert",
    "Social Media Manager",
    "Software Developer",
    "Software Engineer",
    "Technical Wroter",
    "UI Designer",
    "UX Designer",
    "Virtual Assistant",
];
export const SKILLS = [
    "Top skills",
    "Trending skills",
    "Top skills in US",
    "Project catalog",
]
export const BUTTONS = [
    { title: 'Post a job', subtitle: 'and hire a pro' },
    { title: 'Post a job', subtitle: 'and hire a pro' },
    { title: 'Post a job', subtitle: 'and hire a pro' }
]