export const JOB_TITLES = [
    "Data Entry Specialist",
    "Vide Editors",
    "Data Analyst",
    "Shopify Developer",
    "Ruby on Rails Developer",
    "Andriod Developer",
    "Bookkeeper",
    "Content Writer",
    "Copywriter",
    "Database Admin",
    "Data Scientist",
    "Front-end developer",
    "Game Developer",
    "Graphic Designer",
    "Javascript Developer",
    "Logo Designer",
    "Mobile App Developer",
    "PHP developer",
    "Python Developer",
    "Resume Writer",
    "SEO Expert",
    "Social Media Manager",
    "Software Developer",
    "Software Engineer",
    "Technical Wroter",
    "UI Designer",
    "UX Designer",
    "Virtual Assistant",
];
export const SKILLS = [
    "Top skills",
    "Trending skills",
    "Top skills in US",
    "Project catalog",
]
export const BUTTONS = [
    { title: 'Post a job', subtitle: 'and hire a pro' },
    { title: 'Post a job', subtitle: 'and hire a pro' },
    { title: 'Post a job', subtitle: 'and hire a pro' }
]